FogBugz #166591: Rocketboards poky builds using wrong toolchain
This fix is to change the toolchain used to build poky if it is pulled
from RBO

Signed-off-by: Tien Hock Loh <thloh@altera.com>

diff --git a/meta-altera/scripts/altera-setup-builddir b/meta-altera/scripts/altera-setup-builddir
--- a/meta-altera/scripts/altera-setup-builddir
+++ b/meta-altera/scripts/altera-setup-builddir
@@ -92,6 +92,51 @@ fi
 unset OECORELOCALCONF
 unset OECORELAYERCONF
 
+# Now try to check for the external toolchain
+grep EXTERNAL_TOOLCHAIN $BUILDDIR/conf/site.conf > /dev/null
+if [ $? != 0 ]
+then
+    # The EXTERNAL_TOOLCHAIN variable doesn't exist, this poky is from rocketboards.org
+    echo "Please enter the linaro toolchain installation path. Linaro toolchain version 4.7-2012.11-20121123 is required."
+    echo "If the toolchain folder is empty, linaro 4.7-2012.11-20121123 will be downloaded and installed to the path"
+    echo "Hit enter to use default directory at ./linaro-toolchain"
+    read TOOLCHAIN_FOLDER
+
+    if [ "x$TOOLCHAIN_FOLDER" == "x" ]; then
+        TOOLCHAIN_FOLDER="./linaro-toolchain"
+    fi
+
+    if [ -e "$TOOLCHAIN_FOLDER" ]; then
+        echo "Toolchain folder exists, proceeding without downloading toolchain"
+        echo "Checking toolchain version"
+        "$TOOLCHAIN_FOLDER"/bin/arm-linux-gnueabihf-gcc --version | grep 2012.11-20121123 > /dev/null
+        if [ $? != 0 ]; then
+            echo "Toolchain version not supported. Please rerun \"source altera-init\" and specify a correct Linaro toolchain"
+            exit -1
+        else
+            echo "Toolchain version match, proceeding"
+            echo "TCLIBC = \"external-linaro-toolchain\"" >> $BUILDDIR/conf/site.conf
+            echo "TCMODE = \"external-linaro\"" >> $BUILDDIR/conf/site.conf
+            echo "EXTERNAL_TOOLCHAIN = \"$TOOLCHAIN_FOLDER\"" >> $BUILDDIR/conf/site.conf
+        fi
+    else
+        set -e
+        mkdir -p "$TOOLCHAIN_FOLDER"
+        pushd "$TOOLCHAIN_FOLDER"
+        echo "Downloading linaro 4.7-2012.11-20121123 toolchain"
+        wget https://launchpad.net/linaro-toolchain-binaries/trunk/2012.11/+download/gcc-linaro-arm-linux-gnueabihf-4.7-2012.11-20121123_linux.tar.bz2
+        bunzip2 gcc-linaro-arm-linux-gnueabihf-4.7-2012.11-20121123_linux.tar.bz2
+        tar xf gcc-linaro-arm-linux-gnueabihf-4.7-2012.11-20121123_linux.tar
+        rm gcc-linaro-arm-linux-gnueabihf-4.7-2012.11-20121123_linux.tar
+        mv gcc-linaro-arm-linux-gnueabihf-4.7-2012.11-20121123_linux/* .
+        rmdir gcc-linaro-arm-linux-gnueabihf-4.7-2012.11-20121123_linux
+        popd
+        echo "TCLIBC = \"external-linaro-toolchain\"" >> $BUILDDIR/conf/site.conf
+        echo "TCMODE = \"external-linaro\"" >> $BUILDDIR/conf/site.conf
+        echo "EXTERNAL_TOOLCHAIN = \"$TOOLCHAIN_FOLDER\"" >> $BUILDDIR/conf/site.conf
+    fi
+fi
+
 cat <<EOM
 
 ### Shell environment set up for builds. ###
